#!/bin/sh

# Location
DWNDIR="/home/$USER/manga/aot/"

CHAPS=$(curl http://manganelos.com/attack-on-titan-chapter-1 |
       	pup 'select option text{}' | sort -u -k 2 -n |
	grep '\S' | sed 's/:/-/' | cut -d' ' -f2
)


RANGE=$( echo $CHAPS | tr ' ' '\n' | sed -n -e $(echo $CHAPS | tr ' ' '\n' | grep -n $1 | head -1 | cut -d':' -f1),$(echo $CHAPS | tr ' ' '\n' | grep -n $2 | head -1 | cut -d':' -f1)p)

for CH in $RANGE
do
	curl http://manganelos.com/attack-on-titan-chapter-$CH |
       		pup 'p#arraydata text{}' |
       		tr ',' '\n' |
       		xargs -n 1 curl -LO --create-dirs --output-dir $DWNDIR$CH &&
		notify-send -t 5000 "Chapter $CH is ready!" "Start reading by going to $DWNDIR$CH."
done
